# Generated by Django 6.0.7 on 2026-07-23 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('resume_text', models.TextField(blank=True)),
                ('job_description', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_responses', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('final_report', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIInterviewQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('user_answer', models.TextField(blank=True)),
                ('evaluation_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qas', to='ai_interview.aiinterviewsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
