# Generated by Django 6.0.7 on 2026-07-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Internship', 'Internship'), ('Part-Time', 'Part-Time'), ('Remote', 'Remote')], default='Full-Time', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Online Assessment', 'Online Assessment'), ('Technical Interview', 'Technical Interview'), ('HR Interview', 'HR Interview'), ('Final Interview', 'Final Interview'), ('Offer Received', 'Offer Received'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Applied', max_length=50),
        ),
    ]
