# Generated by Django 6.0.7 on 2026-07-22 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(default='Full Stack Engineer', help_text='Target Career Role', max_length=100)),
                ('experience_level', models.CharField(choices=[('Entry', 'Entry Level (0-2 yrs)'), ('Mid', 'Mid Level (2-5 yrs)'), ('Senior', 'Senior Level (5-8 yrs)'), ('Lead', 'Lead / Staff (8+ yrs)')], default='Mid', max_length=20)),
                ('gemini_api_key', models.CharField(blank=True, help_text='Optional custom Google Gemini API Key', max_length=255, null=True)),
                ('theme_preference', models.CharField(choices=[('dark', 'Dark Theme'), ('light', 'Light Theme')], default='dark', max_length=10)),
                ('bio', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
