# Generated by Django 6.0.7 on 2026-07-22 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=255)),
                ('file', models.FileField(upload_to='resumes/')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_skills', models.JSONField(blank=True, default=list)),
                ('parsed_sections', models.JSONField(blank=True, default=dict)),
                ('ats_score', models.IntegerField(default=0)),
                ('ats_breakdown', models.JSONField(blank=True, default=dict)),
                ('ats_feedback', models.JSONField(blank=True, default=list)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
